#!/data/data/com.termux/files/usr/bin/bash

# Universal Project Dumper Script - FIXED VERSION
# Created by: AkNG
# Date: November 17, 2025
# Purpose: Generate complete project documentation with file structure and all code files

PROJECT_ROOT=$(pwd)
PROJECT_NAME=$(basename "$PROJECT_ROOT")
OUTPUT_FILE="$PROJECT_ROOT/${PROJECT_NAME}_project_dump.txt"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

CODE_EXTENSIONS=(
    "js" "jsx" "ts" "tsx"
    "py" "pyw"
    "java" "kt" "kts"
    "c" "cpp" "cc" "h" "hpp"
    "cs" "go" "rs" "php" "rb" "swift"
    "sh" "bash" "zsh"
    "html" "htm" "css" "scss"
    "json" "xml" "yaml" "yml"
    "md" "txt" "sql"
    "dart" "vue" "svelte"
)

EXCLUDE_DIRS=(
    "node_modules" ".git" ".venv" "venv" "env"
    "__pycache__" ".idea" ".vscode"
    "build" "dist" ".gradle" "target"
    "bin" "obj" ".next" ".nuxt" "coverage"
)

echo "=========================================="
echo "Universal Project Dumper - FIXED"
echo "=========================================="
echo "Project: $PROJECT_NAME"
echo "Location: $PROJECT_ROOT"
echo ""

> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << HEADER
================================================================================
                         PROJECT CODE DUMP: $PROJECT_NAME
================================================================================

Project Name: $PROJECT_NAME
Project Root: $PROJECT_ROOT
Generated: $TIMESTAMP
Generated by: Universal Project Dumper v1.1 (Fixed)

================================================================================
                              TABLE OF CONTENTS
================================================================================

1. Project File Structure (Tree View)
2. Project Statistics
3. All Code Files (with full content)

================================================================================
HEADER

add_section() {
    cat >> "$OUTPUT_FILE" << SECTION

================================================================================
                           $1
================================================================================

SECTION
}

add_section "1. PROJECT FILE STRUCTURE (Tree View)"

echo "Generating file structure..." >&2

if command -v tree &> /dev/null; then
    tree -a -I "$(IFS='|'; echo "${EXCLUDE_DIRS[*]}")" "$PROJECT_ROOT" >> "$OUTPUT_FILE" 2>&1
else
    find "$PROJECT_ROOT" -print 2>/dev/null | head -100 >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

add_section "2. PROJECT STATISTICS"

echo "Calculating project statistics..." >&2

echo "=== File Count by Extension ===" >> "$OUTPUT_FILE"
for ext in "${CODE_EXTENSIONS[@]}"; do
    count=$(find "$PROJECT_ROOT" -type f -name "*.$ext" 2>/dev/null | grep -v -E "$(IFS='|'; echo "${EXCLUDE_DIRS[*]}")" | wc -l)
    if [ "$count" -gt 0 ]; then
        echo ".$ext files: $count" >> "$OUTPUT_FILE"
    fi
done

echo "" >> "$OUTPUT_FILE"
echo "=== Total Statistics ===" >> "$OUTPUT_FILE"

add_section "3. ALL CODE FILES (Full Content)"

echo "Dumping all code files..." >&2

file_count=0

for ext in "${CODE_EXTENSIONS[@]}"; do
    while IFS= read -r filepath; do
        if [ -f "$filepath" ]; then
            # Skip if in excluded directory
            skip=0
            for exclude_dir in "${EXCLUDE_DIRS[@]}"; do
                if [[ "$filepath" == *"/$exclude_dir/"* ]]; then
                    skip=1
                    break
                fi
            done
            
            if [ $skip -eq 1 ]; then
                continue
            fi
            
            ((file_count++))
            
            rel_path="${filepath#$PROJECT_ROOT/}"
            filename=$(basename "$filepath")
            file_ext="${filename##*.}"
            file_size=$(wc -c < "$filepath" 2>/dev/null || echo "0")
            line_count=$(wc -l < "$filepath" 2>/dev/null || echo "0")
            
            cat >> "$OUTPUT_FILE" << FILEHEAD

================================================================================
[$file_count] $rel_path
================================================================================
File: $filename
Path: $filepath
Type: .$file_ext
Size: $file_size bytes
Lines: $line_count
--------------------------------------------------------------------------------

FILEHEAD
            
            cat "$filepath" >> "$OUTPUT_FILE" 2>/dev/null
            
            echo "" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            
            echo "  [$file_count] Processed: $rel_path" >&2
        fi
    done < <(find "$PROJECT_ROOT" -type f -name "*.$ext" 2>/dev/null)
done

cat >> "$OUTPUT_FILE" << FOOTER

================================================================================
                              END OF PROJECT DUMP
================================================================================

Project: $PROJECT_NAME
Total Files Dumped: $file_count
Generated: $TIMESTAMP
Output File: $OUTPUT_FILE

This file contains the complete project structure and all code files.
Generated by: Universal Project Dumper v1.1 (Fixed)
Author: AkNG

================================================================================
FOOTER

echo ""
echo "✅ Project dump completed successfully!"
echo ""
echo "📊 Statistics:"
echo "  - Files processed: $file_count"
echo "  - Output file: $OUTPUT_FILE"
echo "  - File size: $(du -h "$OUTPUT_FILE" 2>/dev/null | cut -f1 || echo "unknown")"
echo ""
echo "📄 View the dump:"
echo "  less $OUTPUT_FILE"
echo "  nano $OUTPUT_FILE"
echo ""
echo "=========================================="
