#!/bin/bash

OUTPUT_FILE="FlintWeatherAI_project_dump.txt"
PROJECT_NAME="FlintWeatherAI"
PROJECT_ROOT=$(pwd)

echo "=========================================="
echo "Universal Project Dumper v2.0"
echo "=========================================="
echo "Project: $PROJECT_NAME"
echo "Location: $PROJECT_ROOT"
echo ""

# Start the dump file
cat > "$OUTPUT_FILE" << EOF
================================================================================
                         PROJECT CODE DUMP: $PROJECT_NAME
================================================================================

Project Name: $PROJECT_NAME
Project Root: $PROJECT_ROOT
Generated: $(date '+%Y-%m-%d %H:%M:%S')
Generated by: Universal Project Dumper v2.0

================================================================================
                              TABLE OF CONTENTS
================================================================================

1. Project File Structure (Tree View)
2. Project Statistics
3. All Code Files (with full content)

================================================================================

EOF

# Add tree structure
echo "Generating file structure..."
echo "================================================================================" >> "$OUTPUT_FILE"
echo "                           1. PROJECT FILE STRUCTURE (Tree View)" >> "$OUTPUT_FILE"
echo "================================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tree -I 'venv|__pycache__|*.pyc|node_modules' >> "$OUTPUT_FILE" 2>/dev/null || find . -not -path '*/venv/*' -not -path '*/__pycache__/*' -not -name '*.pyc' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Statistics
echo "Calculating project statistics..."
echo "================================================================================" >> "$OUTPUT_FILE"
echo "                              2. PROJECT STATISTICS" >> "$OUTPUT_FILE"
echo "================================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

PYTHON_FILES=$(find . -name "*.py" -not -path "*/venv/*" -not -path "*/__pycache__/*" | wc -l)
JS_FILES=$(find . -name "*.js" -not -path "*/venv/*" -not -path "*/node_modules/*" | wc -l)
HTML_FILES=$(find . -name "*.html" -not -path "*/venv/*" | wc -l)
CSS_FILES=$(find . -name "*.css" -not -path "*/venv/*" | wc -l)
TOTAL_FILES=$(find . -type f -not -path "*/venv/*" -not -path "*/__pycache__/*" -not -name "*.pyc" | wc -l)

echo "File Count by Extension:" >> "$OUTPUT_FILE"
echo "  .py files:    $PYTHON_FILES" >> "$OUTPUT_FILE"
echo "  .js files:    $JS_FILES" >> "$OUTPUT_FILE"
echo "  .html files:  $HTML_FILES" >> "$OUTPUT_FILE"
echo "  .css files:   $CSS_FILES" >> "$OUTPUT_FILE"
echo "  Total files:  $TOTAL_FILES" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Dump all code files
echo "Dumping all code files..."
echo "================================================================================" >> "$OUTPUT_FILE"
echo "                           3. ALL CODE FILES (Full Content)" >> "$OUTPUT_FILE"
echo "================================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

FILE_COUNT=0

# Function to dump a file
dump_file() {
    local file="$1"
    local rel_path="${file#./}"
    
    echo "───────────────────────────────────────────────────────────────────────────────" >> "$OUTPUT_FILE"
    echo "FILE: $rel_path" >> "$OUTPUT_FILE"
    echo "───────────────────────────────────────────────────────────────────────────────" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$file" >> "$OUTPUT_FILE" 2>/dev/null || echo "[Binary or unreadable file]" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    ((FILE_COUNT++))
}

# Dump Python files
find . -name "*.py" -not -path "*/venv/*" -not -path "*/__pycache__/*" -type f | while read file; do
    dump_file "$file"
done

# Dump JS files
find . -name "*.js" -not -path "*/venv/*" -not -path "*/node_modules/*" -type f | while read file; do
    dump_file "$file"
done

# Dump HTML files
find . -name "*.html" -not -path "*/venv/*" -type f | while read file; do
    dump_file "$file"
done

# Dump CSS files
find . -name "*.css" -not -path "*/venv/*" -type f | while read file; do
    dump_file "$file"
done

# Dump config files
for ext in txt json yaml yml sh md; do
    find . -maxdepth 2 -name "*.$ext" -not -name "$OUTPUT_FILE" -type f | while read file; do
        dump_file "$file"
    done
done

echo "================================================================================" >> "$OUTPUT_FILE"
echo "                              END OF PROJECT DUMP" >> "$OUTPUT_FILE"
echo "================================================================================" >> "$OUTPUT_FILE"

# Final statistics
OUTPUT_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)

echo ""
echo "✅ Project dump completed successfully!"
echo ""
echo "📊 Statistics:"
echo "  - Files processed: $FILE_COUNT"
echo "  - Output file: $PROJECT_ROOT/$OUTPUT_FILE"
echo "  - File size: $OUTPUT_SIZE"
echo ""
echo "📄 View the dump:"
echo "  less $PROJECT_ROOT/$OUTPUT_FILE"
echo "  nano $PROJECT_ROOT/$OUTPUT_FILE"
echo ""
echo "=========================================="
